# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PIA_message_pb2 as PIA__message__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class PIAMessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/PythonIntelligenceAgent.PIAMessageService/Publish',
                request_serializer=PIA__message__pb2.PublishMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_unary(
                '/PythonIntelligenceAgent.PIAMessageService/Subscribe',
                request_serializer=PIA__message__pb2.SubscribeMessage.SerializeToString,
                response_deserializer=PIA__message__pb2.ResponseSubscribe.FromString,
                )
        self.UnSubscribe = channel.unary_unary(
                '/PythonIntelligenceAgent.PIAMessageService/UnSubscribe',
                request_serializer=PIA__message__pb2.SubscribeMessage.SerializeToString,
                response_deserializer=PIA__message__pb2.ResponseSubscribe.FromString,
                )
        self.Request = channel.unary_unary(
                '/PythonIntelligenceAgent.PIAMessageService/Request',
                request_serializer=PIA__message__pb2.RequestMessage.SerializeToString,
                response_deserializer=PIA__message__pb2.ResponseMessage.FromString,
                )


class PIAMessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnSubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PIAMessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=PIA__message__pb2.PublishMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=PIA__message__pb2.SubscribeMessage.FromString,
                    response_serializer=PIA__message__pb2.ResponseSubscribe.SerializeToString,
            ),
            'UnSubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.UnSubscribe,
                    request_deserializer=PIA__message__pb2.SubscribeMessage.FromString,
                    response_serializer=PIA__message__pb2.ResponseSubscribe.SerializeToString,
            ),
            'Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Request,
                    request_deserializer=PIA__message__pb2.RequestMessage.FromString,
                    response_serializer=PIA__message__pb2.ResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PythonIntelligenceAgent.PIAMessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PIAMessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PythonIntelligenceAgent.PIAMessageService/Publish',
            PIA__message__pb2.PublishMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PythonIntelligenceAgent.PIAMessageService/Subscribe',
            PIA__message__pb2.SubscribeMessage.SerializeToString,
            PIA__message__pb2.ResponseSubscribe.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnSubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PythonIntelligenceAgent.PIAMessageService/UnSubscribe',
            PIA__message__pb2.SubscribeMessage.SerializeToString,
            PIA__message__pb2.ResponseSubscribe.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PythonIntelligenceAgent.PIAMessageService/Request',
            PIA__message__pb2.RequestMessage.SerializeToString,
            PIA__message__pb2.ResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
