# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PIA_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PIA_message.proto\x12\x17PythonIntelligenceAgent\x1a\x1bgoogle/protobuf/empty.proto\"u\n\x0ePublishMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\x05\x12\x11\n\tpublisher\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x13\n\x0bpublish_key\x18\x04 \x01(\t\x12\x15\n\rpublish_value\x18\x05 \x01(\t\"g\n\x10SubscribeMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\x05\x12\x12\n\nsubscriber\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x19\n\x11subscribe_pattern\x18\x04 \x01(\t\"\xaf\x01\n\x11ResponseSubscribe\x12\x12\n\nmessage_id\x18\x01 \x01(\x05\x12@\n\x0fresponse_status\x18\x02 \x01(\x0e\x32\'.PythonIntelligenceAgent.ResponseStatus\x12\x44\n\x11subscribe_message\x18\x03 \x01(\x0b\x32).PythonIntelligenceAgent.SubscribeMessage\"u\n\x0eRequestMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\x05\x12\x11\n\trequester\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x13\n\x0brequest_key\x18\x04 \x01(\t\x12\x15\n\rrequest_value\x18\x05 \x01(\t\"\xba\x01\n\x0fResponseMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\x05\x12\x11\n\tresponser\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x14\n\x0cresponse_key\x18\x04 \x01(\t\x12\x16\n\x0eresponse_value\x18\x05 \x01(\t\x12@\n\x0frequest_message\x18\x06 \x01(\x0b\x32\'.PythonIntelligenceAgent.RequestMessage*\'\n\x0eResponseStatus\x12\t\n\x05\x41LLOW\x10\x00\x12\n\n\x06\x44\x45NIED\x10\x01\x32\x8f\x03\n\x11PIAMessageService\x12L\n\x07Publish\x12\'.PythonIntelligenceAgent.PublishMessage\x1a\x16.google.protobuf.Empty\"\x00\x12\x64\n\tSubscribe\x12).PythonIntelligenceAgent.SubscribeMessage\x1a*.PythonIntelligenceAgent.ResponseSubscribe\"\x00\x12\x66\n\x0bUnSubscribe\x12).PythonIntelligenceAgent.SubscribeMessage\x1a*.PythonIntelligenceAgent.ResponseSubscribe\"\x00\x12^\n\x07Request\x12\'.PythonIntelligenceAgent.RequestMessage\x1a(.PythonIntelligenceAgent.ResponseMessage\"\x00\x62\x06proto3')

_RESPONSESTATUS = DESCRIPTOR.enum_types_by_name['ResponseStatus']
ResponseStatus = enum_type_wrapper.EnumTypeWrapper(_RESPONSESTATUS)
ALLOW = 0
DENIED = 1


_PUBLISHMESSAGE = DESCRIPTOR.message_types_by_name['PublishMessage']
_SUBSCRIBEMESSAGE = DESCRIPTOR.message_types_by_name['SubscribeMessage']
_RESPONSESUBSCRIBE = DESCRIPTOR.message_types_by_name['ResponseSubscribe']
_REQUESTMESSAGE = DESCRIPTOR.message_types_by_name['RequestMessage']
_RESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['ResponseMessage']
PublishMessage = _reflection.GeneratedProtocolMessageType('PublishMessage', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHMESSAGE,
  '__module__' : 'PIA_message_pb2'
  # @@protoc_insertion_point(class_scope:PythonIntelligenceAgent.PublishMessage)
  })
_sym_db.RegisterMessage(PublishMessage)

SubscribeMessage = _reflection.GeneratedProtocolMessageType('SubscribeMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEMESSAGE,
  '__module__' : 'PIA_message_pb2'
  # @@protoc_insertion_point(class_scope:PythonIntelligenceAgent.SubscribeMessage)
  })
_sym_db.RegisterMessage(SubscribeMessage)

ResponseSubscribe = _reflection.GeneratedProtocolMessageType('ResponseSubscribe', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESUBSCRIBE,
  '__module__' : 'PIA_message_pb2'
  # @@protoc_insertion_point(class_scope:PythonIntelligenceAgent.ResponseSubscribe)
  })
_sym_db.RegisterMessage(ResponseSubscribe)

RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTMESSAGE,
  '__module__' : 'PIA_message_pb2'
  # @@protoc_insertion_point(class_scope:PythonIntelligenceAgent.RequestMessage)
  })
_sym_db.RegisterMessage(RequestMessage)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEMESSAGE,
  '__module__' : 'PIA_message_pb2'
  # @@protoc_insertion_point(class_scope:PythonIntelligenceAgent.ResponseMessage)
  })
_sym_db.RegisterMessage(ResponseMessage)

_PIAMESSAGESERVICE = DESCRIPTOR.services_by_name['PIAMessageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSESTATUS._serialized_start=785
  _RESPONSESTATUS._serialized_end=824
  _PUBLISHMESSAGE._serialized_start=75
  _PUBLISHMESSAGE._serialized_end=192
  _SUBSCRIBEMESSAGE._serialized_start=194
  _SUBSCRIBEMESSAGE._serialized_end=297
  _RESPONSESUBSCRIBE._serialized_start=300
  _RESPONSESUBSCRIBE._serialized_end=475
  _REQUESTMESSAGE._serialized_start=477
  _REQUESTMESSAGE._serialized_end=594
  _RESPONSEMESSAGE._serialized_start=597
  _RESPONSEMESSAGE._serialized_end=783
  _PIAMESSAGESERVICE._serialized_start=827
  _PIAMESSAGESERVICE._serialized_end=1226
# @@protoc_insertion_point(module_scope)
